(()=>{
const UI={
  en:{navAtlas:'Atlas',navTimeline:'Timeline',navLibrary:'Library',navUpdates:'Auto updates',eyebrow:'Curated research atlas',heroTitle:'A living map of sound, light, and computational imaging.',heroSubtitle:'A selective, auto-audited guide to acoustic–optical fusion, coded acoustics, sonar reconstruction, acoustic holography, photoacoustic imaging, and acousto-optic imaging across top venues.',browseLibrary:'Browse library',viewUpdates:'View auto updates',metricPapers:'curated papers',metricYears:'year span',metricVenues:'venue groups',signalTitle:'Update policy',signalText:'Every run resolves final journal/conference venues when arXiv papers have accepted versions.',roadmapEyebrow:'Reading roadmap',roadmapTitle:'How the field is evolving',roadmapSubtitle:'The papers are organized as research threads rather than a flat bibliography.',timelineEyebrow:'Chronology',timelineTitle:'Development timeline',timelineSubtitle:'Click a year to filter the library and inspect how the emphasis shifts over time.',clearYear:'Show all years',themeEyebrow:'Topic structure',themeTitle:'Topic map',themeSubtitle:'A compact overview of recurring technical directions.',libraryEyebrow:'Curated library',libraryTitle:'Verified papers',librarySubtitle:'Filter by year, venue, topic, and relevance. Chinese mode provides natural Chinese titles and reading notes.',footerPdf:'PDF links point only to open or legitimate sources.',footerPrivacy:'Public metadata uses neutral project language and avoids private research-context notes.',updatesEyebrow:'Automated discovery',updatesTitle:'Auto-reviewed paper updates.',updatesSubtitle:'The scheduled workflow searches public scholarly sources every 6 hours. A curation agent scores venue quality, source reliability, topical relevance, PDF availability, and duplicate status.',autoAuditTitle:'Agent audit policy',autoAuditText:'High-confidence papers can be promoted automatically. Borderline records remain visible here for transparency.',candidateTitle:'Candidate stream',candidateSubtitle:'Each item keeps its audit status, score, and source.',backToIndex:'← Back to paper index',allYears:'All years',allVenues:'All venue groups',allTopics:'All topics',allRelevance:'All relevance',core:'Core',related:'Related',details:'Details',publisher:'Publisher',pdf:'PDF',project:'Project',code:'Code',doi:'DOI',venue:'Venue',date:'Year / date',relevance:'Relevance',lastVerified:'Last verified',highlight:'Highlight',why:'Why included',download:'PDF / download note',sources:'Verification sources',bibtex:'BibTeX',showing:(n,t)=>`${n} of ${t} shown`},
  zh:{navAtlas:'总览',navTimeline:'时间线',navLibrary:'文献库',navUpdates:'自动更新',eyebrow:'精选研究图谱',heroTitle:'声、光与计算成像的动态文献地图。',heroSubtitle:'这不是普通论文列表，而是一份持续更新的阅读图谱：串联声光融合、声学编码、声呐重建、声学全息、光声成像与声光成像在顶刊顶会中的关键进展。',browseLibrary:'浏览文献库',viewUpdates:'查看自动更新',metricPapers:'精选论文',metricYears:'时间跨度',metricVenues:'期刊/会议组',signalTitle:'更新原则',signalText:'若 arXiv 论文已有正式接收/发表版本，系统会优先标记最终期刊或会议，arXiv 仅作为开放预印本来源。',roadmapEyebrow:'阅读路线',roadmapTitle:'这条脉络如何展开',roadmapSubtitle:'按研究问题组织文献，而不是把论文简单堆成列表。',timelineEyebrow:'时间线',timelineTitle:'发展脉络',timelineSubtitle:'点击年份即可筛选文献，观察不同阶段的研究重心如何变化。',clearYear:'显示全部年份',themeEyebrow:'主题结构',themeTitle:'主题地图',themeSubtitle:'用几个主线快速把握这个交叉方向。',libraryEyebrow:'精选文献库',libraryTitle:'已核验论文',librarySubtitle:'可按年份、venue、主题和相关度筛选；中文模式提供更自然的标题译名和导读。',footerPdf:'PDF 链接仅指向开放或合法来源。',footerPrivacy:'公开元数据使用中性项目语言，不包含私人研究背景。',updatesEyebrow:'自动发现',updatesTitle:'自动审核的论文更新',updatesSubtitle:'GitHub Actions 每 6 小时检索公开学术来源；审核 Agent 会评估 venue 质量、来源可靠性、主题相关性、PDF 可用性和重复状态。',autoAuditTitle:'Agent 审核策略',autoAuditText:'高置信论文可自动进入正式库；边界样本保留在这里，便于透明检查。',candidateTitle:'候选流',candidateSubtitle:'每条候选保留审核状态、分数和来源。',backToIndex:'← 返回文献图谱',allYears:'全部年份',allVenues:'全部 venue group',allTopics:'全部主题',allRelevance:'全部相关度',core:'核心',related:'相关',details:'详情',publisher:'出版社',pdf:'PDF',project:'项目',code:'代码',doi:'DOI',venue:'期刊 / 会议',date:'年份 / 日期',relevance:'相关度',lastVerified:'最近核验',highlight:'看点',why:'收录理由',download:'PDF / 下载说明',sources:'核验来源',bibtex:'BibTeX',showing:(n,t)=>`显示 ${n} / ${t} 篇`}
};
const titleCN={
'brodjian2026-single-view-seafloor-sonar-rendering':'单视角成像声呐的可微渲染海底恢复','colladogonzalez2026-opti-acoustic-volumetric-mapping':'通用声光传感器融合与体积建图','chen2026-sovis-sonar-visual-dataset':'SOVIS：水下声呐-视觉跨模态数据集','xie2024-bathymetric-sonar-neural-volume-rendering':'基于神经体渲染的成像声呐海底测绘','qadri2022-neural-implicit-imaging-sonar':'基于成像声呐的神经隐式表面重建',
'ruan2026-photoacoustic-mesoscopy':'非侵入式光声计算介观成像：面向纵向脑成像','chew2025-acoustic-reliefs':'声学浮雕：面向声散射控制的几何表面','brandmueller2025-photoacoustic-meta-optics':'超构光学赋能的光声显微成像','li2025-ultrasound-sar-nlos':'超声合成孔径非视域成像','qu2025-zsplat':'Z-Splat：面向相机–声呐融合的 Z 轴高斯重建','huynh2025-all-optical-3d-photoacoustic-scanner':'用于临床血管成像的快速全光学三维光声扫描仪','qadri2024-aoneus':'AONeuS：声光传感器融合的神经渲染框架','christopoulos2024-temporal-acoustic-point-holography':'时间编码的声学点全息','chen2024-pattern':'PATTERN：时间编码光声断层成像与全脑跨模态分析','lin2024-ah-view':'声学全息诱导的虚拟增强波导，用于经颅脑光声成像','brown2024-computational-ultrasound-4d':'脑血流动力学的四维计算超声成像','reed2023-neural-sas':'相干合成孔径声呐的神经体重建','chakravarthula2023-seeing-with-sound':'用声音看见：远距离声学波束形成辅助多模态场景理解','hirayama2022-high-speed-acoustic-holography-scattering':'存在任意散射物时的高速声学全息','hazan2022-silicon-photonics-acoustic-detector':'用于光声微断层成像的硅光子声学探测器','kothari2020-wave-based-imaging':'学习波动成像中的几何结构','martinezplasencia2020-gs-pat':'GS-PAT：相控阵换能器的高速多点声场计算','jang2020-space-gated-microscopy':'声光相互作用驱动的深组织空间门控显微成像','doktofsky2020-acousto-optic-speckle-decorrelation':'利用散斑去相关突破声学衍射极限的声光成像','hirayama2019-volumetric-display-acoustic-trapping':'声学俘获体显示：视觉、触觉与声音的统一呈现','lindell2019-acoustic-nlos':'声学非视域成像'};
const polishedCN={
'brodjian2026-single-view-seafloor-sonar-rendering':'把成像声呐的物理投影过程写成可微渲染器，从单张声呐图像反推出高度场，适合作为声学 forward model 与优化反演的参考。','colladogonzalez2026-opti-acoustic-volumetric-mapping':'面向复杂水下环境的相机-声呐融合建图工作，强调视觉的空间细节与声学量测稳健性的互补。','chen2026-sovis-sonar-visual-dataset':'提供真实配对的声呐-视觉数据，对跨模态预测、监督设计和水下融合感知有直接数据价值。','xie2024-bathymetric-sonar-neural-volume-rendering':'将神经体渲染用于前视成像声呐的海底测绘，并把声呐波束模式纳入可微估计。','qadri2022-neural-implicit-imaging-sonar':'用神经隐式表面和可微声学体渲染拟合成像声呐，是后续声光神经融合路线的重要声学基础。',
'ruan2026-photoacoustic-mesoscopy':'把光声介观成像推进到非侵入、纵向脑成像场景，体现了光声系统在生命科学长期观测中的潜力。','chew2025-acoustic-reliefs':'从“成像系统”延展到“声场可编程表面”，适合作为声学编码结构和声散射控制的设计参考。','brandmueller2025-photoacoustic-meta-optics':'把超构光学引入光声显微激发路径，展示了光学编码硬件与声学读出的紧耦合设计。','li2025-ultrasound-sar-nlos':'用空气超声和合成孔径思想重建隐藏三维场景，是声学 NLOS 走向更高分辨率的重要进展。','qu2025-zsplat':'将声呐深度线索纳入 3D Gaussian Splatting，针对水下受限视角重建中的深度缺失问题给出清晰解法。','huynh2025-all-optical-3d-photoacoustic-scanner':'全光学超声探测与三维光声扫描结合，代表光声系统向临床可用硬件演进。','qadri2024-aoneus':'把 RGB 与 imaging sonar 放入统一的神经渲染框架，是声光融合三维重建方向的代表性顶会工作。','christopoulos2024-temporal-acoustic-point-holography':'把时间维度纳入声学全息点场控制，为更灵活的相控阵声场编码提供路径。','chen2024-pattern':'通过时间编码提升全脑光声层析的速度与跨模态分析能力，是编码光声成像的重要系统化尝试。','lin2024-ah-view':'用声学全息塑造有效声传播通道来改善经颅光声成像，体现“声场设计服务成像”的思路。','brown2024-computational-ultrasound-4d':'以复杂声场和物理模型降低采样约束，展示计算超声在四维脑血流成像中的潜力。','reed2023-neural-sas':'把相干合成孔径声呐与神经体表示结合，连接了波动成像物理和神经场重建。','chakravarthula2023-seeing-with-sound':'强调声学信号对视觉感知的互补性，适合作为多模态声视觉感知的入口文献。','hirayama2022-high-speed-acoustic-holography-scattering':'处理复杂散射环境下的高速声学全息计算，是声场控制走向真实环境的关键一步。','hazan2022-silicon-photonics-acoustic-detector':'用硅光子器件实现小型声学探测，连接集成光子学与光声微断层成像。','kothari2020-wave-based-imaging':'从学习理论角度刻画波动成像几何，为光声、地震等反问题提供统一视角。','martinezplasencia2020-gs-pat':'声学相控阵多点声场生成的基础算法之一，为声学全息和空中触觉奠定工程基础。','jang2020-space-gated-microscopy':'利用声光相互作用抑制深组织散射，体现声场调制对光学显微的增强作用。','doktofsky2020-acousto-optic-speckle-decorrelation':'通过散斑去相关突破声学衍射极限，是声光成像超分辨方向的重要物理机制工作。','hirayama2019-volumetric-display-acoustic-trapping':'用声学俘获实现体显示与触觉反馈，展示声场控制在可视化界面中的想象力。','lindell2019-acoustic-nlos':'声学非视域成像的基础论文之一，用低成本声学硬件恢复隐藏几何。'};
const summaryEN={'li2025-ultrasound-sar-nlos':'A Nature Portfolio paper demonstrating ultrasound synthetic aperture reconstruction for acoustic non-line-of-sight imaging.','qadri2024-aoneus':'A SIGGRAPH neural rendering framework for acoustic–optical sensor fusion in underwater 3D reconstruction.','qu2025-zsplat':'A TPAMI paper that uses sonar cues to improve depth-axis reconstruction in camera–sonar Gaussian splatting.','reed2023-neural-sas':'A TOG/SIGGRAPH paper connecting coherent synthetic aperture sonar with neural volumetric reconstruction.','lindell2019-acoustic-nlos':'A foundational CVPR paper on recovering hidden 3D geometry with time-resolved acoustic sensing.','brodjian2026-single-view-seafloor-sonar-rendering':'A CVPRW paper that recovers seafloor height from a single imaging-sonar image using differentiable sonar rendering.','xie2024-bathymetric-sonar-neural-volume-rendering':'A self-supervised imaging-sonar reconstruction paper using neural volume rendering and differentiable sonar modeling.','qadri2022-neural-implicit-imaging-sonar':'A neural implicit reconstruction method for forward-looking imaging sonar with a differentiable acoustic renderer.'};
const threads=[
  {k:'foundations',en:'Foundations: wave geometry and hidden scenes',zh:'基础问题：波动几何与隐藏场景',keys:['NLOS','wave-based','time-resolved','hidden'],descEn:'Early work establishes what acoustic waves can reveal when optical visibility is limited.',descZh:'早期工作回答一个基础问题：当光学视线受限时，声波究竟还能恢复什么几何信息。'},
  {k:'fields',en:'Programmable acoustic fields',zh:'可编程声场',keys:['holography','phased','field','acoustic trapping','temporal coding'],descEn:'Acoustic holography and phased arrays turn sound fields into a computational design medium.',descZh:'声学全息与相控阵把“声场”变成可计算、可设计、可控制的媒介。'},
  {k:'fusion',en:'Acoustic–optical fusion and sonar reconstruction',zh:'声光融合与声呐重建',keys:['sonar','camera-sonar','acoustic-optical','Gaussian','neural rendering','synthetic aperture sonar','opti-acoustic'],descEn:'Vision, sonar, and neural representations converge for underwater and wave-based 3D reconstruction.',descZh:'视觉、声呐与神经表示开始汇合，推动水下三维重建和波动成像重建。'},
  {k:'photo',en:'Photoacoustic and acousto-optic imaging systems',zh:'光声与声光成像系统',keys:['photoacoustic','optoacoustic','acousto-optic','microscopy','tomography'],descEn:'Optical excitation and acoustic readout are increasingly co-designed for biomedical imaging.',descZh:'光激发与声学读出不再分离，而是被共同设计成面向生命科学和医学成像的系统。'}
];
let lang=localStorage.getItem('aoi-lang')||'en',papers=[],candidates=[],last={},activeYear='',activeTopic='';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;'}[c]));
function T(k){let v=(UI[lang]||UI.en)[k]||UI.en[k]||k;return typeof v==='function'?v:v}
function clean(s){return String(s??'').replace(/与你的[“"][^。]*[”"][^。]*。?/g,lang==='zh'?'该论文与公开追踪主题直接相关，并提供可核验来源。':'This paper matches the public tracker scope and provides verifiable sources.')}
async function load(p,f){try{let r=await fetch(p,{cache:'no-store'});return r.ok?await r.json():f}catch(e){return f}}
function uniq(arr){const m=new Map();arr.forEach(p=>{if(p&&p.id&&!m.has(p.id))m.set(p.id,p)});return [...m.values()]}
function setLang(l){lang=l||lang;localStorage.setItem('aoi-lang',lang);document.documentElement.lang=lang==='zh'?'zh-CN':'en';$$('[data-i18n]').forEach(e=>e.textContent=T(e.dataset.i18n));$$('.lang button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));let q=$('#q');if(q)q.placeholder=lang==='zh'?'搜索题目、作者、期刊/会议、主题关键词...':'Search title, author, venue, or topic...';render()}
function link(u,l){return u?`<a href="${esc(u)}" target="${u.startsWith('paper.html')?'_self':'_blank'}" rel="noopener">${esc(l)}</a>`:''}
function topics(p){return (p.topics||[]).join(', ')||'acoustic–optical imaging'}
function yearOf(p){return String(p.year||String(p.publication_date||'').slice(0,4)||'Unknown')}
function enSummary(p){return clean(p.summary_en||summaryEN[p.id]||`A ${p.venue||'scholarly'} paper on ${topics(p)}.`)}
function zhSummary(p){return clean(polishedCN[p.id]||p.summary_cn||`这篇论文关注 ${topics(p)}，可作为相关方向的阅读入口。`)}
function enWhy(p){return clean(p.why_include_en||`Included because it is relevant to ${topics(p)} and comes from a prioritized venue or reliable scholarly source.`)}
function zhWhy(p){return clean(p.why_include_cn||`收录原因：主题覆盖 ${topics(p)}，且来源较可靠。`)}
function threadCount(th){return papers.filter(p=>th.keys.some(k=>[p.title,p.venue,topics(p),p.summary_cn].join(' ').toLowerCase().includes(k.toLowerCase()))).length}
function renderRoadmap(){let el=$('#roadmap');if(!el)return;el.innerHTML=threads.map((t,i)=>`<article class="road-card" data-step="0${i+1}"><h3>${esc(lang==='zh'?t.zh:t.en)}</h3><p>${esc(lang==='zh'?t.descZh:t.descEn)}</p><div class="mini">${threadCount(t)} ${lang==='zh'?'篇相关论文':'related papers'}</div></article>`).join('')}
function renderYearline(){let el=$('#yearline');if(!el)return;let counts={};papers.forEach(p=>counts[yearOf(p)]=(counts[yearOf(p)]||0)+1);let years=Object.keys(counts).sort((a,b)=>b.localeCompare(a)),max=Math.max(...Object.values(counts),1);el.innerHTML=years.map(y=>`<button class="year-node ${activeYear===y?'active':''}" data-year="${esc(y)}"><b>${esc(y)}</b><span>${counts[y]} ${lang==='zh'?'篇论文':'papers'}</span><div class="bar"><i style="width:${Math.max(12,counts[y]/max*100)}%"></i></div></button>`).join('');$$('.year-node').forEach(b=>b.onclick=()=>{activeYear=b.dataset.year;let yr=$('#year');if(yr)yr.value=activeYear;filter();renderYearline();document.getElementById('library')?.scrollIntoView({behavior:'smooth',block:'start'})});let clear=$('#clearYear');if(clear)clear.onclick=()=>{activeYear='';let yr=$('#year');if(yr)yr.value='';filter();renderYearline()}}
function renderTopicMap(){let el=$('#topicMap');if(!el)return;let counts={};papers.flatMap(p=>p.topics||[]).forEach(t=>counts[t]=(counts[t]||0)+1);let topicsSorted=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,18);let venues={};papers.forEach(p=>{let v=p.venue_group||p.venue||'Other';venues[v]=(venues[v]||0)+1});let venueRows=Object.entries(venues).sort((a,b)=>b[1]-a[1]).slice(0,10);el.innerHTML=`<div class="topic-cloud"><h3>${lang==='zh'?'高频主题':'Frequent topics'}</h3><div class="chips">${topicsSorted.map(([t,n])=>`<button class="chip" data-topic="${esc(t)}">${esc(t)} <em>${n}</em></button>`).join('')}</div></div><div class="venue-panel"><h3>${lang==='zh'?'Venue 分布':'Venue distribution'}</h3><div class="venue-list">${venueRows.map(([v,n])=>`<div class="venue-row"><b>${esc(v)}</b><span>${n}</span></div>`).join('')}</div></div>`;$$('.chip[data-topic]').forEach(c=>c.onclick=()=>{activeTopic=c.dataset.topic;let t=$('#topic');if(t)t.value=activeTopic;filter();document.getElementById('library')?.scrollIntoView({behavior:'smooth',block:'start'})})}
function card(p){let zh=lang==='zh',rel=p.relevance==='core'?'core':'related';let txt=[p.title,titleCN[p.id],p.authors,p.venue,p.venue_group,topics(p),zhSummary(p),enSummary(p),yearOf(p)].join(' ').toLowerCase();return `<article class="card" data-text="${esc(txt)}" data-year="${esc(yearOf(p))}" data-venue="${esc(p.venue_group||'')}" data-topics="${esc(topics(p))}" data-rel="${esc(p.relevance||'')}"><div class="card-top"><span class="tag">${esc(p.venue_group||p.venue||'Venue')}</span><span class="year-pill">${esc(yearOf(p))}</span></div><h3>${esc(p.title)}${zh?`<span class="title-cn">${esc(p.title_cn||titleCN[p.id]||p.title)}</span>`:''}</h3><p class="meta">${esc(p.authors||'')}</p><p class="meta">${esc(p.venue||'')} · <span class="badge ${rel}">${esc(zh?(p.relevance==='core'?T('core'):T('related')):p.relevance)}</span></p><div class="tags">${(p.topics||[]).slice(0,5).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="highlight">${esc(zh?zhSummary(p):enSummary(p))}</div><div class="why">${esc(zh?zhWhy(p):enWhy(p))}</div><div class="links">${link('paper.html?id='+encodeURIComponent(p.id),T('details'))}${link(p.primary_url,T('publisher'))}${link(p.pdf_url,T('pdf'))}${link(p.project_url,T('project'))}${link(p.code_url,T('code'))}</div></article>`}
function candidateCard(c){let st=c.status||'candidate',cls=st.includes('promoted')?'agent-promoted':st.includes('approved')?'agent-approved':'candidate',txt=[c.title,c.authors,c.venue,c.source,c.matched_query,st,(c.reasons||[]).join(' ')].join(' ').toLowerCase();return `<article class="card" data-text="${esc(txt)}"><div class="card-top"><span class="tag">${esc(c.venue||c.source||'Candidate')}</span><span class="year-pill">${esc(c.year||'')}</span></div><h3>${esc(c.title||'Untitled')}</h3><p class="meta">${esc(c.authors||'')}</p><p class="meta">score ${esc(c.score??'—')} · ${esc(c.source||'—')} · <span class="badge ${cls}">${esc(st)}</span></p><div class="tags">${(c.reasons||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="highlight">${esc(lang==='zh'?(c.summary_cn||'自动审核候选论文。'):(c.summary_en||('Matched query: '+(c.matched_query||'N/A'))))}</div><div class="why">audit: ${esc((c.agent_audit||{}).decision||st)} · first: ${esc(c.first_seen||'—')} · last: ${esc(c.last_seen||'—')}</div><div class="links">${link(c.primary_url,T('publisher'))}${link(c.pdf_url,T('pdf'))}${c.doi?link('https://doi.org/'+c.doi,T('doi')):''}</div></article>`}
function controls(){let y=$('#year'),v=$('#venue'),t=$('#topic'),r=$('#rel');if(!v||document.body.dataset.page!=='index')return;let ys=[...new Set(papers.map(yearOf))].sort((a,b)=>b.localeCompare(a)),vs=[...new Set(papers.map(p=>p.venue_group).filter(Boolean))].sort(),ts=[...new Set(papers.flatMap(p=>p.topics||[]))].sort();y.innerHTML=`<option value="">${T('allYears')}</option>`+ys.map(x=>`<option>${esc(x)}</option>`).join('');v.innerHTML=`<option value="">${T('allVenues')}</option>`+vs.map(x=>`<option>${esc(x)}</option>`).join('');t.innerHTML=`<option value="">${T('allTopics')}</option>`+ts.map(x=>`<option>${esc(x)}</option>`).join('');r.innerHTML=`<option value="">${T('allRelevance')}</option><option value="core">${T('core')}</option><option value="related">${T('related')}</option>`;[y,v,t,r,$('#q')].forEach(x=>x&&x.addEventListener('input',()=>{activeYear=y.value;activeTopic=t.value;filter();renderYearline()}))}
function filter(){let q=($('#q')?.value||'').toLowerCase(),y=$('#year')?.value||activeYear||'',v=$('#venue')?.value||'',t=$('#topic')?.value||activeTopic||'',r=$('#rel')?.value||'',n=0,cards=$$('.card');cards.forEach(c=>{let ok=(!q||(c.dataset.text||'').includes(q))&&(!y||c.dataset.year===y)&&(!v||c.dataset.venue===v)&&(!t||(c.dataset.topics||'').includes(t))&&(!r||c.dataset.rel===r);c.classList.toggle('hidden',!ok);if(ok)n++});let count=$('#count');if(count)count.textContent=UI[lang].showing(n,cards.length)}
function renderIndex(){controls();renderRoadmap();renderYearline();renderTopicMap();$('#grid').innerHTML=papers.map(card).join('');filter()}
function render(){let page=document.body.dataset.page;if(page==='index'&&papers.length)renderIndex();if(page==='updates'){if(candidates.length){$('#grid').innerHTML=candidates.map(candidateCard).join('')}else{$('#grid').innerHTML=`<p class="note">${lang==='zh'?'暂无候选。':'No candidates yet.'}</p>`}$('#q')?.addEventListener('input',filter);filter()}if(page==='paper'&&papers.length)paperDetail()}
function bib(p){let key=(p.id||'paper').replace(/[^a-zA-Z0-9]/g,'').slice(0,40),typ=(p.venue_type||'').startsWith('journal')?'article':'inproceedings';return `@${typ}{${key},\n  title = {${p.title}},\n  author = {${String(p.authors||'').replace(/;\s*/g,' and ')}},\n  year = {${p.year||''}},\n  ${typ==='article'?'journal':'booktitle'} = {${p.venue||''}},\n  url = {${p.primary_url||''}}\n}`}
function row(k,v){return `<dt>${esc(k)}</dt><dd>${v||'—'}</dd>`}
function paperDetail(){let id=new URLSearchParams(location.search).get('id'),p=papers.find(x=>x.id===id)||papers[0],zh=lang==='zh';if(!p)return;document.title=p.title+' · Acoustic–Optics Imaging';$('#detail').innerHTML=`<p class="eyebrow">${esc(p.venue_group||p.venue||'')}</p><h1>${esc(p.title)}</h1>${zh?`<p class="title-cn">${esc(p.title_cn||titleCN[p.id]||p.title)}</p>`:''}<p class="meta">${esc(p.authors||'')}</p><div class="tags">${(p.topics||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><dl class="kv">${row(T('venue'),esc(p.venue||''))}${row(T('date'),esc((p.year||'')+(p.publication_date?' / '+p.publication_date:'')))}${row(T('relevance'),`<span class="badge ${p.relevance==='core'?'core':'related'}">${esc(zh?(p.relevance==='core'?T('core'):T('related')):p.relevance)}</span>`)}${row(T('doi'),p.doi?link('https://doi.org/'+p.doi,p.doi):'—')}${row(T('publisher'),link(p.primary_url,p.primary_url||'—'))}${row(T('pdf'),link(p.pdf_url,p.pdf_url||'—'))}${row(T('project'),link(p.project_url,p.project_url||'—'))}${row(T('code'),link(p.code_url,p.code_url||'—'))}${row(T('lastVerified'),esc(p.last_verified||'—'))}</dl><h2>${T('highlight')}</h2><p>${esc(zh?zhSummary(p):enSummary(p))}</p><h2>${T('why')}</h2><p>${esc(zh?zhWhy(p):enWhy(p))}</p><h2>${T('download')}</h2><p class="note">${esc(p.download_note||'')}</p><h2>${T('sources')}</h2><ul>${(p.sources||[]).map(s=>`<li>${link(s,s)}</li>`).join('')}</ul><h2>${T('bibtex')}</h2><pre>${esc(bib(p))}</pre>`}
document.addEventListener('DOMContentLoaded',async()=>{$$('.lang button').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));setLang(lang);let page=document.body.dataset.page;if(page==='index'||page==='paper'){let base=await load('data/papers.json',[]),focus=await load('data/focus_papers.json',[]);papers=uniq([...focus,...base]);papers.sort((a,b)=>String(b.publication_date||b.year||'').localeCompare(String(a.publication_date||a.year||'')));last=await load('data/last_update.json',{});candidates=await load('data/candidates.json',[]);let years=[...new Set(papers.map(yearOf))].sort();$('#m-papers')&&($('#m-papers').textContent=papers.length);$('#m-years')&&($('#m-years').textContent=years.length?`${years[0]}–${years.at(-1)}`:'—');$('#m-venues')&&($('#m-venues').textContent=[...new Set(papers.map(p=>p.venue_group).filter(Boolean))].length);}if(page==='updates'){candidates=await load('data/candidates.json',[]);last=await load('data/last_update.json',{});$('#m-candidates')&&($('#m-candidates').textContent=candidates.length);$('#m-promoted')&&($('#m-promoted').textContent=last.promoted_count??candidates.filter(c=>String(c.status||'').includes('promoted')).length);$('#m-latest')&&($('#m-latest').textContent=(last.last_run||'—').slice(0,19));}render()});
})();
